services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    restart: always
  testback:
    image: postgres
    ports:
      - ${TEST_POSTGRESQL_ADDON_PORT}:5432
    environment:
      POSTGRES_USER: ${TEST_POSTGRESQL_ADDON_USER}
      POSTGRES_PASSWORD: ${TEST_POSTGRESQL_ADDON_PASSWORD}
      POSTGRES_DB: ${TEST_POSTGRESQL_ADDON_DB}
    restart: always
  adminer:
    image: adminer
    container_name: adminer
    environment:
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: database
    ports:
      - 8080:8080
  adminer_test:
    image: adminer
    container_name: adminer_test
    environment:
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: test_database
    ports:
      - 8082:8080
  maildev:
      image: maildev/maildev
      command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
      ports:
        - "8081:80"
        - "25:25"